server:
  env_name: ${APP_ENV:vllm}

llm:
  mode: openailike
  max_new_tokens: 16000
  tokenizer: mistralai/Mistral-7B-Instruct-v0.3
  temperature: 0.1

embedding:
  mode: azopenai
  embed_dim: 1536

openai:
  api_key: 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
  model: mistralai/mistral-7b-instruct-v0.3
  embedding_api_key: ${OPENAI_API_KEY:}
  api_base: https://openrouter.ai/api/v1
  request_timeout: 600.0

huggingface:
  embedding_hf_model_name: BAAI/bge-small-en-v1.5
  access_token: ${HUGGINGFACE_TOKEN:}